version: '3.5'

services:
  db_auth:
    container_name: stream
    ports:
       - '5432:5432'
    environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=admin
    image: postgres:14-alpine3.17